# Generated by Django 4.1.5 on 2023-01-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs_turi',
            name='nomi',
            field=models.CharField(max_length=999),
        ),
    ]
