# Generated by Django 4.1.5 on 2023-01-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_alter_kurs_turi_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='royxat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('ish', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('vaqt', models.CharField(max_length=100)),
                ('kurs', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='malumot',
            name='capshn',
            field=models.CharField(max_length=999),
        ),
    ]
