# Generated by Django 4.1.5 on 2023-02-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_royxat_alter_malumot_capshn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='nomi',
        ),
        migrations.DeleteModel(
            name='malumot',
        ),
        migrations.DeleteModel(
            name='royxat',
        ),
        migrations.DeleteModel(
            name='kurs',
        ),
        migrations.DeleteModel(
            name='kurs_turi',
        ),
    ]
