# Generated by Django 4.1.5 on 2023-02-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myfiles', '0004_remove_kurs_nomi_delete_malumot_delete_royxat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Royxat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=300)),
                ('manzil', models.CharField(max_length=300)),
                ('vaqt', models.CharField(max_length=300)),
                ('telefon', models.CharField(max_length=300)),
                ('kurs', models.CharField(max_length=300)),
                ('ish', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.fan')),
            ],
        ),
    ]
