# Generated by Django 4.1.5 on 2023-02-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royxat',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.fan'),
        ),
    ]
