# Generated by Django 4.1.5 on 2023-02-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_alter_royxat_kurs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kurs',
        ),
    ]
