# Generated by Django 4.1.5 on 2023-02-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_delete_kurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.fan')),
            ],
        ),
    ]
