# Generated by Django 4.1.5 on 2023-02-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_kurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fan',
            old_name='fan',
            new_name='fans',
        ),
    ]
