# Generated by Django 4.1.5 on 2023-02-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_tugma'),
    ]

    operations = [
        migrations.CreateModel(
            name='tugma_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tugma_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
            ],
        ),
    ]
