# Generated by Django 4.1.5 on 2023-02-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0011_tugma_en_tugma_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='til',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('til', models.CharField(max_length=100)),
            ],
        ),
    ]
