# Generated by Django 4.1.5 on 2023-02-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_til'),
    ]

    operations = [
        migrations.RenameField(
            model_name='til',
            old_name='til',
            new_name='lang',
        ),
    ]
