# Generated by Django 4.1.5 on 2023-02-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0013_rename_til_til_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='til',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
