# Generated by Django 4.1.5 on 2023-02-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0014_til_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='obhavo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('shaxar', models.CharField(max_length=100)),
                ('vaqt', models.CharField(max_length=100)),
            ],
        ),
    ]
