# Generated by Django 4.2.23 on 2025-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0015_obhavo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=300)),
                ('user_ismi', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='ism',
        ),
        migrations.DeleteModel(
            name='obhavo',
        ),
        migrations.RemoveField(
            model_name='royxat',
            name='kurs',
        ),
        migrations.DeleteModel(
            name='til',
        ),
        migrations.DeleteModel(
            name='tugma',
        ),
        migrations.DeleteModel(
            name='tugma_en',
        ),
        migrations.DeleteModel(
            name='tugma_ru',
        ),
        migrations.DeleteModel(
            name='fan',
        ),
        migrations.DeleteModel(
            name='kurs',
        ),
        migrations.DeleteModel(
            name='Royxat',
        ),
    ]
