# Generated by Django 4.2.23 on 2025-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0016_user_remove_kurs_ism_delete_obhavo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
            ],
        ),
    ]
