# Generated by Django 4.2.23 on 2025-07-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0017_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='tg_user',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
