# Generated by Django 4.2.23 on 2025-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0018_alter_admin_tg_user_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='ismi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
