# Generated by Django 4.2.23 on 2025-07-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0019_admin_ismi'),
    ]

    operations = [
        migrations.CreateModel(
            name='kanallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(blank=True, max_length=300, null=True)),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('ismi', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
