# Generated by Django 4.2.23 on 2025-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0020_kanallar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balans',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
