# Generated by Django 4.2.23 on 2025-08-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0021_user_balans'),
    ]

    operations = [
        migrations.CreateModel(
            name='summa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.CharField(max_length=300)),
            ],
        ),
    ]
