# Generated by Django 4.2.23 on 2025-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0022_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='til',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
