# Generated by Django 4.2.23 on 2025-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0023_user_til'),
    ]

    operations = [
        migrations.CreateModel(
            name='shablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=300, null=True)),
                ('institut', models.CharField(blank=True, max_length=300, null=True)),
                ('ism_fam', models.CharField(blank=True, max_length=300, null=True)),
                ('saxifa_soni', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
