# Generated by Django 4.2.23 on 2025-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0024_shablon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shablon',
            name='til',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
