# Generated by Django 4.2.23 on 2025-08-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0025_shablon_til'),
    ]

    operations = [
        migrations.CreateModel(
            name='referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('referal_id', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
