# Generated by Django 4.2.23 on 2025-08-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0026_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='referal',
            name='user_id',
            field=models.CharField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
