# Generated by Django 4.2.23 on 2025-08-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0027_alter_referal_balance_alter_referal_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shablon',
            name='saxifa_soni',
        ),
    ]
