# Generated by Django 4.2.23 on 2025-08-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0028_remove_shablon_saxifa_soni'),
    ]

    operations = [
        migrations.CreateModel(
            name='shablon_pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=300, null=True)),
                ('pre_id', models.CharField(blank=True, max_length=300, null=True)),
                ('ism_fam', models.CharField(blank=True, max_length=300, null=True)),
                ('til', models.CharField(blank=True, max_length=300, null=True)),
                ('slayid_soni', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
