# Generated by Django 4.2.23 on 2025-08-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0029_shablon_pre'),
    ]

    operations = [
        migrations.AddField(
            model_name='shablon_pre',
            name='pre_tili',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
