# Generated by Django 4.2.23 on 2025-08-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0030_shablon_pre_pre_tili'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shablon_pre',
            old_name='pre_id',
            new_name='bg_num',
        ),
    ]
