# Generated by Django 4.2.23 on 2025-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0031_rename_pre_id_shablon_pre_bg_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShablonPre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(help_text='The Telegram user ID who created this template', max_length=300, verbose_name='Telegram User ID')),
                ('bg_num', models.PositiveSmallIntegerField(help_text='Selected background design number', verbose_name='Background Number')),
                ('ism_fam', models.CharField(blank=True, max_length=300, null=True, verbose_name='Author Name')),
                ('til', models.CharField(default='uz', help_text='Language code for the template content', max_length=10, verbose_name='Template Language')),
                ('slayid_soni', models.PositiveSmallIntegerField(help_text='Number of slides in the presentation', verbose_name='Slide Count')),
                ('pre_tili', models.CharField(default='uz', help_text='Language used for the interface when creating', max_length=10, verbose_name='Interface Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Presentation Template',
                'verbose_name_plural': 'Presentation Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='shablon_pre',
        ),
    ]
