# Generated by Django 4.2.23 on 2025-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0032_shablonpre_delete_shablon_pre'),
    ]

    operations = [
        migrations.CreateModel(
            name='shablon_pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=300, null=True)),
                ('bg_num', models.CharField(blank=True, max_length=300, null=True)),
                ('ism_fam', models.CharField(blank=True, max_length=300, null=True)),
                ('til', models.CharField(blank=True, max_length=300, null=True)),
                ('slayid_soni', models.CharField(blank=True, max_length=300, null=True)),
                ('pre_tili', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ShablonPre',
        ),
    ]
