# Generated by Django 4.2.23 on 2025-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0033_shablon_pre_delete_shablonpre'),
    ]

    operations = [
        migrations.CreateModel(
            name='shablon_kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=300, null=True)),
                ('institut', models.CharField(blank=True, max_length=300, null=True)),
                ('ism_fam', models.CharField(blank=True, max_length=300, null=True)),
                ('sahifa_soni', models.CharField(blank=True, max_length=300, null=True)),
                ('til', models.CharField(blank=True, max_length=300, null=True)),
                ('kurs_tili', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='shablon',
        ),
    ]
